backend:
  name: github
  repo: Riyaspn/hadow-architecture
  branch: main

# Where images should be saved in the repo
media_folder: "public/projects"
public_folder: "/projects"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
